'''
Deciding what's a word
Before you build up to the winning pipeline, it will be useful to look a little deeper into how the text features will be processed.

In this exercise, you will use CountVectorizer on the training data X_train (preloaded into the workspace) to see the effect of tokenization on punctuation.

Remember, since CountVectorizer expects a vector, you'll need to use the preloaded function, combine_text_columns before fitting to the training data.

'''

# Import the CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

# Create the text vector
text_vector = combine_text_columns(X_train)

# Create the token pattern: TOKENS_ALPHANUMERIC
TOKENS_ALPHANUMERIC = '[A-Za-z0-9]+(?=\\s+)'

# Instantiate the CountVectorizer: text_features
text_features = CountVectorizer(token_pattern=TOKENS_ALPHANUMERIC)

# Fit text_features to the text vector
text_features.fit(text_vector)

# Print the first 10 tokens
print(text_features.get_feature_names()[:10])


'''
textvector example
198       Supplemental *  Operation and Maintenance of P...
209       REPAIR AND MAINTENANCE SERVICES  PUPIL TRANSPO...
750       Personal Services - Teachers   TCHER 5TH GRADE...
931       General Supplies      General Supplies  Instru...
1524      Supplies and Materials  Community Services    ...
1770      ATHLETIC SUPPLEMENTS             COACHING SUPP...
1951      CONFERENCE REGISTRATION              School  I...
2542      EMPLOYEE BENEFITS  ARRA - STIMULUS Speech Lang...
2640      OTHER SUPPORT PERSONNEL          MANAGER, GEOG...
2939      RETIREMENT CONTRIB.  GENERAL FUND Social Worke...
3029      CONTRA BENEFITS  GENERAL FUND Teacher, Element...
3395      EMPLOYEE BENEFITS TEACHER SUBS GENERAL FUND Te...
4490      CONTRA BENEFITS  GENERAL FUND Geographic Syste...
4593      SALARIES OF REGULAR EMPLOYEES SEVERE DISABILIT...
5050      SALARIES OF REGULAR EMPLOYEES  GENERAL FUND Te...
5066      Office Supplies  Support Services--Pupils    G...
5370      SALARIES OF PART TIME EMPLOYEE  GENERAL FUND T...
5916         Teacher-Instructional Support        Misc G...
6029      Personal Services - Health Services     Specia...
6054      Extra Duty Pay/Overtime For Support Personnel ...
6730      Overtime *  Operation and Maintenance of Plant...
6794      Travel And Subsistence - Employee Only      Tr...
7041      Salaries Or Wages For Support Personnel  "Titl...
7151      EMPLOYEE BENEFITS SPEECH & LANGUAGE GENERAL FU...
8384      SUPPLIES  PRIMARY GRADES PROGRAM       INSTRUC...
8468      PURCHASE OF EQUIPMENT-OTHER THAN BUSES AND COM...
8815      ALL OTHER SUPPLEMENTS            TEACHER, ASD ...
8960      Extra Duty Pay/Overtime For Support Personnel ...
9722      OTHER PERSONAL SERVICES          CLERICAL/TCHR...
10876     Salaries And Wages For Teachers And Other Prof...
                                ...                        
444647    Salaries And Wages For Teachers And Other Prof...
444719    PURCHASE OF EQUIPMENT-OTHER THAN BUSES AND COM...
444808    EMPLOYEE BENEFITS  FEDERAL GDPG FUND - FY  Spe...
445206    Purchased Services  Support Services - Instruc...
445678     SECURITY SERVICES LOCAL SPECIAL POLICE OFFICE...
445947    EMPLOYEE BENEFITS  GENERAL FUND ELA General As...
445981    TELEPHONE/FACSIMILE SERVICES  GENERAL FUND (bl...
446032    SALARIES OF REGULAR EMPLOYEES  GENERAL FUND Pr...
446102    RETIREMENT                       FAMILY/SCHOOL...
446199    SEWER FEES OPERATIONS - UTILITIES GENERAL FUND...
446528    EMPLOYEE BENEFITS  GENERAL FUND Principal Regu...
446628    EMPLOYER PD MED CONTRIBUTION  GENERAL FUND Exe...
446668    OTHER CERTIFIED                  LIBRARY/MEDIA...
447383    SALARIES OF REGULAR EMPLOYEES  GENERAL FUND Te...
447387    Coaching Supplement   INTRAMURAL ASSISTANT    ...
447492     SCHOOL ADMINISTRATIVE SUPPORT LOCAL ADMINISTR...
447887    OTHER PURCHASED SERVICES             School  M...
448122    Extra Duty Pay/Overtime For Support Personnel ...
448298    MILEAGE REIMBURSEMENT MULTILINGUAL OUTREACH GE...
448628    Furniture And Equipment      Other Equipment A...
448733    SUPPLIES  PRE-KINDERGARTEN PGM-LOTTERY INSTRUC...

text_vector[198]
'Supplemental *  Operation and Maintenance of Plant Services    Non-Certificated Salaries And Wages  Care and Upkeep of Building Services    Title I - Disadvantaged Children/Targeted Assistance TITLE I CARRYOVER '

'''